version: '3'
services:
  bokeh:
    build: ./face-bokeh
    image: face-bokeh
    container_name: bokeh
    ports:
      - "8004:8000"

  emotion:
    build: ./face-emotion
    image: face-emotion
    container_name: emotion
    ports:
      - "8005:8000"
  
  triton:
    image: nvcr.io/nvidia/tritonserver:22.06-py3
    container_name: triton
    hostname: triton
    env_file: .aws.env
    expose:
      - "8000"
      - "8001"
      - "8002"
    ports:
      - "8001:8001"
      - "8002:8002"
      - "8003:8000"
    ipc: host
    command: bash -c "tritonserver --model-repository=s3://jolascua-bucket/models/"
#['tritonserver', '--model-repository=s3://shobha-mur-week1/models/']
  myapp:
    build: .
    image: myapp
    container_name: bokeh-emotion-app
    depends_on:
      - bokeh
      - emotion
      - triton
    ports:
      - "8000:8000"