version: '3'
services:
  bokeh:
    build: ./face-bokeh
    image: face-bokeh
    container_name: face-bokeh
    expose:
      - "8000"
    ports:
      - "8004:8000"

  emotion:
    build: ./face-emotion
    image: face-emotion
    container_name: face-emotion
    expose:
      - "8000"
    ports:
      - "8005:8000"
  
  triton:
    image: nvcr.io/nvidia/tritonserver:22.06-py3
    container_name: tritonserver
    env_file: .aws.env
    expose:
      - "8000"
      - "8001"
      - "8002"
    ports:
      - "8001:8001"
      - "8002:8002"
      - "8003:8000"
    ipc: host
    command: bash -c "tritonserver --model-repository=s3://jolascua-bucket/models/"

  myapp:
    build: .
    image: myapp
    container_name: bokeh-emotion
    depends_on:
      - bokeh
      - emotion
      - triton
    expose:
      - "8000"
    ports:
      - "8000:8000"